- name: Stat directories if they exists
  stat: 
    path: "{{ item }}"
  register: GIT_DIR
  with_items:
  - "{{ GIT_CONFIG }}"
  - "{{ GIT_LOGS }}"
  - "{{ GIT_DATA }}"
  - "{{ GIT_RUNNER_CONFIG }}"
  - "{{ GIT_CERT }}"
- name: Create directories if they don't exists
  file: 
    path: "{{ item.item }}" 
    state: directory
  when: item.stat.exists == false
  with_items:
  - "{{ GIT_DIR.results }}"
- name: Get docker network info.
  docker_network_info: 
    name: "{{ DOCKER_NETWORK }}"
  register: DOCKER_NET
- name: Print if not existss
  debug:
    msg: " The required network {{ 'exists' if DOCKER_NET.exists else 'does not exists' }}"
- name: Create docker network
  docker_network:
    name: "{{ DOCKER_NETWORK }}"
- name: Copy gitlab certs to container
  copy: src="{{ item }}" dest="{{ GIT_CERT }}"
  with_items:
  - server-cert.pem
  - server-key.pem
