version: '3'
services:
  gitlab:
    image: kube1.netcracker.com:5000/sagar/gitlab/gitlab-ce:v1
    container_name: GitLab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://ops-master.netcracker.com:50443'
        gitlab_rails['time_zone'] = 'America/Chicago'
        gitlab_rails['backup_keep_time'] = 14515200
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 3
        logging['logrotate_frequency'] = "weekly"
        logging['logrotate_rotate'] = 52
        logging['logrotate_compress'] = "compress"
        logging['logrotate_method'] = "copytruncate"
        logging['logrotate_delaycompress'] = "delaycompress"
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server-cert.pem"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server-key.pem"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        nginx['logrotate_frequency'] = "weekly"
        nginx['logrotate_rotate'] = 52
        nginx['logrotate_compress'] = "compress"
        nginx['logrotate_method'] = "copytruncate"
        nginx['logrotate_delaycompress'] = "delaycompress"
    ports:
      - '50443:443'
      - '50022:22'
    volumes:
      - /srv/gitlab/config:/etc/gitlab:Z
      - /srv/gitlab/certs:/etc/ssl/certs/gitlab:Z
      - /srv/gitlab/logs:/var/log/gitlab:Z
      - /srv/gitlab/data:/var/opt/gitlab:Z
    networks:
      dev-net:
        aliases:
          - gitlab.ops-master.netcracker.com
  gitlab-runner:
    image: kube1.netcracker.com:5000/sagar/gitlab/gitlab-runner:v1
    container_name: GitLab_Runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - /srv/gitlab/config1/gitlab-runner:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    networks:
      - dev-net

networks:
  dev-net:
    external:
      name: development


