---

- name: set SElinux permissive for access to volumes from containers (old)
  shell: semanage permissive -a svirt_lxc_net_t
  become: yes
  ignore_errors: True

- name: set SElinux permissive for access to volumes from containers (new)
  shell: semanage permissive -a container_t
  become: yes
  ignore_errors: True

- name: stop and remove GitLab docker container
  shell: "docker stop {{ item }}  && docker rm  {{ item }}"
  ignore_errors: yes
  with_items:
  - GitLab
  - GitLab_Runner

- name: Run Gitlab
  shell: docker-compose up -d chdir={{ DOCKER_COMP }} 

- name: initializing Gitlab
  block:
    - name: Wait for Gitlab to come up
      uri:
        url: "https://{{ GIT_HOST }}:50443"
        validate_certs: no
        status_code: 200
      register: result
      until: result is succeeded
      retries: 500
      delay: 10
