---

- name: Replace contains in docker-compose
  copy: src=docker-compose.yml.j2 dest="{{ role_path }}/files/docker-compose.yml"

- name: Prepare the docker compose.
  replace:
    path: "{{role_path }}/files/docker-compose.yml"
    regexp: "{{ item.regexp1 }}"
    replace: "{{ item.replace }}"
  with_items:
  - { regexp1: 'GITLAB_IMG', replace: "{{ GIT_IMG | default('docker.io/gitlab/gitlab-ce:latest') }}" }
  - { regexp1: 'URL', replace: "https://{{ GIT_HOST | default('localhost') }}:50443" }
  - { regexp1: 'ALIAS', replace: "gitlab.{{ GIT_HOST | default('localhost') }}" }
  - { regexp1: 'GITLAB_RUNNER_IMG', replace: "{{ GIT_RUN_IMG | default('docker.io/gitlab/gitlab-runner:latest') }}" }
  - { regexp1: 'GITLAB_NETWORK', replace: "{{ DOCKER_NETWORK }}" }

